FROM php:8.1-cli as base
LABEL maintainer="Martin Brooksbank <martin@bosslabs.co.uk>"

# Install necessary OS packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
        git \
        libzip-dev \
        zlib1g-dev \
        libxml2-dev

# Install necessary PHP packages
RUN docker-php-ext-install \
        zip \
        xml

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Create io directories
RUN mkdir /input
RUN mkdir /output

WORKDIR /app

RUN sed -E -i -e 's/memory_limit = 128M/memory_limit = 1024M/' /usr/local/etc/php/php.ini-production
RUN mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini


ADD ./docker/docker-entrypoint-dev.sh /
RUN chmod +x /docker-entrypoint-dev.sh

EXPOSE 80
CMD ["/docker-entrypoint-dev.sh"]